MassThrust: 150000
MaxAngle: 0.4
mass: 0.027
PIDs:
  Body:
    kp: 0.187
    kd: 0.107
    ki: 0.013
  Yaw:
    kp: -100.0
    kd: -25.0
    ki: 0.0
    minOutput: -200.0
    maxOutput: 200.0
    integratorMin: 0.0
    integratorMax: 0.0
